### ISSUE TITLE
Error when compiling app in build.phonegap.com ( You have not accepted the license agreements of the following SDK components)

### ISSUE THREAD

**Issue by marchdigital** [phonegap/build#627]
I have recently attempted to update my app but I am getting a malformed config.xml error  - I'm not sure what I am supposed to do to fix this as the config.xml has not changed since previous builds ...
 
The error(s) seem to suggest that I need to accept some license agreements - but how do I do that in PhoneGap build ... I am not using (nor have I ever used) Android Studio to create this app?
 
Build Date: 2018-03-13 04:01:43 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-customurlscheme" via npm
Installing "cordova-plugin-customurlscheme" at "4.3.0" for android
Fetching plugin "pushwoosh-pgb-plugin" via npm
Installing "pushwoosh-cordova-plugin" at "7.3" for android
Subproject Path: CordovaLib
Fetching plugin "cordova-plugin-crosswalk-webview" via npm
Installing "cordova-plugin-crosswalk-webview" at "2.4.0" for android
Subproject Path: CordovaLib
 
  After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.
 
  So the minSdkVersion of Cordova project is configured to 16 by default.
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist" at "1.3.3" for android
 
  This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Subproject Path: CordovaLib
null
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
at build_38yx7te0qyc7dd4rqwl9lyqqx.run(/project/build.gradle:138)
org.xwalk:xwalk_core_library:23+
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
The ProjectDependency.getProjectConfiguration() method has been deprecated and is scheduled to be removed in Gradle 4.0.
ModuleDependency.getConfiguration() has been deprecated and is scheduled to be removed in Gradle 4.0. Use ModuleDependency.getTargetConfiguration() instead.
 
FAILURE: Build failed with an exception.
 
* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [ConstraintLayout for Android 1.0.2, Solver for ConstraintLayout 1.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 
BUILD FAILED
 
Total time: 2.459 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
 
* What went wrong:
A problem occurred configuring root project 'project'.
> You have not accepted the license agreements of the following SDK components:
  [ConstraintLayout for Android 1.0.2, Solver for ConstraintLayout 1.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by nicksterFL** [comment]
I have the same issue. Any resolution to this?

**Comment by wfhm** [comment]
Same here.

**Comment by marchdigital** [comment]
Still nothing from Adobe. I gave up and found an alternative for my project using Android Studio, I'll never use Phonegap again - and I am even considering cancelling my Adobe subscription.  I find that I use their bloated software less frequently these days so I doubt I'd miss it.

**Comment by andersborgabiro** [comment]
Are you saying that you are developing a native app instead?

**Comment by marchdigital** [comment]
No - I ended up purchasing a template from Envato to wrap my HTML5 project in. It worked great (and only cost $19) ... https://codecanyon.net/item/universal-android-webview-app/8431507

**Comment by andersborgabiro** [comment]
OK, so no iOS app too, and not much use of plugins then?
