### ISSUE TITLE
Could not find glide.jar (com.github.bumptech.glide:glide:4.3.1)

### ISSUE THREAD

**Issue by wfhm** [phonegap/build#631]
Building apk with Phonegap Build fails with the following exception:

 

    FAILURE: Build failed with an exception.

 

    Could not resolve all files for configuration ':app:debugCompileClasspath'.

    > Could not find glide.jar (com.github.bumptech.glide:glide:4.3.1).

    Searched in the following locations:

    https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.3.1/glide-4.3.1.jar

 

 

    BUILD FAILED in 17s

    at ChildProcess.whenDone (/cordova/node_modules/cordova-common/src/superspawn.js:169:23)

    at emitTwo (events.js:106:13)

    at ChildProcess.emit (events.js:191:7)

    at maybeClose (internal/child_process.js:877:16)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

I have started a new thread on the forum:

https://forums.adobe.com/message/10389096#10389096

It seems that build server cannot reach  https://jcenter.bintray.com/com/github/bumptech/glide/glide/4.3.1/glide-4.3.1.jar location.

The URL is directly accessible from my Mac, and I am able to build locally using Cordova/Phonegap CLI, so it looks like the issue is on PGB side.

**Comment by andersborgabiro** [comment]
Maybe a big leap, but couldn't you use CSS for image loading and animation etc instead?

I'm not sure how you would use glide.jar, except from the platforms/android folder. I understand why it works via CLI if you insert the library yourself. Is it part of a Cordova plugin?
