### ISSUE TITLE
Builds failing (apparently) randomnly

### ISSUE THREAD

**Issue by leon-vg** [phonegap/build#651]
Note: this is a copy of the forum post here: https://forums.adobe.com/thread/2612056

For a couple of months we notice that Android builds appear to be failing randomnly. For example: out of six parallel builds, sometimes only four are build succesfully.

The failed builds appear to have varying logging outputs. Examples of the logging (last lines) are the following. Note that in these cases the same app (with very minor differences) is build, so a cause within the app is not plausible.

The problem appears to occur only on certain times during the day. Perhaps this problem is correlated with the status of the build service?

Many thanks for looking into this problem.

ID: 3525285
```
:app:compileDebugSources  
:app:transformClassesWithStackFramesFixerForDebug  
:app:transformClassesWithDesugarForDebug  
:app:transformClassesWithDexBuilderForDebug  
----- End of the daemon log -----  
  
  
  
  
FAILURE: Build failed with an exception.  
  
  
* What went wrong:  
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)  
  
  
* Try:  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.  
  
  
* Get more help at https://help.gradle.org  
    at ChildProcess.whenDone (/var/gimlet/tmp/46992993428720/3525285/cordova/node_modules/cordova-common/src/superspawn.js:169:23)  
    at emitTwo (events.js:126:13)  
    at ChildProcess.emit (events.js:214:7)  
    at maybeClose (internal/child_process.js:915:16)  
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)  
 ```

Or:

 

ID: 3526639
```
cordova.system.library.4=com.android.support:support-v13:27.+  
cordova.system.library.5=me.leolin:ShortcutBadger:1.1.17@aar  
cordova.system.library.6=com.google.firebase:firebase-messaging:11.6.2  
cordova.gradle.include.5=cordova-plugin-firebase-crash/beta-build.gradle  
--------------------------------------------------------------------------------  
COMPILE OUTPUT  
--------------------------------------------------------------------------------  
 ```

Or:

 

ID: 3526641
```
:app:compileDebugAidl  
:CordovaLib:packageDebugRenderscript NO-SOURCE  
:app:compileDebugRenderscript  
:app:checkDebugManifest  
:app:generateDebugBuildConfig  
:app:prepareLintJar  
:app:generateDebugResValues  
:app:generateDebugResources  
:app:processDebugGoogleServices  
Parsing json file: /var/gimlet/tmp/47158039432560/3526641/app/google-services.json  
:app:mergeDebugResources  
``

**Comment by leon-vg** [comment]
Any progress on this issue? So far no response on this issue or [the forum post](https://forums.adobe.com/thread/2612056).

Thanks for looking into this issue.

**Comment by leon-vg** [comment]
Too bad there has been no response. We have fixed this issue with a workaround - by rebuilding the app via an API-call when the build has failed. Not very elegant but it seems to work.

If there is renewed interest in this issue, please don't hesitate to contact me for more information.
